library(readr)
power <- read_delim("D:/Google Drive/stats begins here/Data Science -John Hopkins/Course 4 Exploratory Data Analysis/Week 1 Programming Assignment/household_power_consumption.txt", ";", escape_double = FALSE, trim_ws = TRUE)
View(power)
d<-as.Date(power$Date,"%d/%m/%Y")
subpower<-power[d=="2007/02/01" | d=="2007/02/02",]
time<-paste(subpower$Date,subpower$Time,sep=" ")
datetime<-strptime(time, "%d/%m/%Y %H:%M:%S")
png(filename = "plot2",width=480,height=480)
with(subpower, plot(datetime,Global_active_power,type='l',xlab="",ylab="Global Active Power(kilowatts)"))
dev.off()